//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 997
        ///1582
        ///1790
        ///1798
        ///1094
        ///1831
        ///1879
        ///1730
        ///1995
        ///1702
        ///1680
        ///1869
        ///1964
        ///1777
        ///1862
        ///1928
        ///1997
        ///1741
        ///1604
        ///1691
        ///1219
        ///1458
        ///1749
        ///1717
        ///1786
        ///1665
        ///1724
        ///1998
        ///1589
        ///1828
        ///1953
        ///1848
        ///1500
        ///1590
        ///1968
        ///1948
        ///1323
        ///1800
        ///1986
        ///679
        ///1907
        ///1916
        ///1820
        ///1661
        ///1479
        ///1808
        ///1824
        ///1825
        ///1952
        ///1666
        ///1541
        ///1791
        ///1906
        ///1638
        ///1557
        ///1999
        ///1710
        ///1549
        ///1912
        ///1974
        ///1628
        ///1748
        ///1411
        ///1978
        ///1865
        ///1932
        ///1839
        ///1892
        ///1981
        ///1807
        ///357
        ///912
        ///1443
        ///1972
        ///1816
        ///1890
        ///1029
        ///1175
        ///1522
        ///1750
        ///2001
        ///1655
        ///1955
        ///1949
        ///1660
        ///233
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13-15 c: cqbhncccjsncqcc
        ///2-3 v: zvdvfd
        ///9-14 b: rbrbnbbbqdfrht
        ///11-12 k: kkkkkkkkkkxqk
        ///4-5 b: bqbbdm
        ///10-12 w: kwwkwwwrwzzwwwwzwswx
        ///1-11 g: grrmgmqgghw
        ///4-5 m: mbmhmvmwdvxmvpw
        ///1-13 n: ndnnnnnnnnnns
        ///11-18 l: lllllllllllllllllll
        ///4-5 c: cccscc
        ///2-4 k: bkfr
        ///9-13 k: lcmsvkknrxtkkksgvkjg
        ///1-2 b: bhwgb
        ///1-4 j: zjjcjj
        ///7-11 g: nnffggdmggr
        ///3-4 z: zzhzz
        ///4-10 g: mggkgvgggmggkggmqg
        ///4-5 n: dcmnl
        ///11-15 s: gzpdvsmnzsshswzs
        ///10-14 x: xmvpxjtlxxhxtpdhsnx
        ///5-15 v: zzhjdpgxlsvphzv
        ///4-8 k: dsfktqchpkk
        ///6-7 j: jzjgjq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
    }
}
